import { init } from "@instantdb/react"
import { useEffect, useState } from "react"

import { PlayerJson, VoteJson } from "$/helpers/types"

const db = init({
  appId: atob(`${import.meta.env.VITE_DB}`),
})

function Vote() {
  const { isLoading, error, data } = db.useQuery({
    players: {
      $: {
        where: {
          and: [{ position: { $isNull: false } }, { position: { $not: "" } }],
        },
      },
    },
    // cannot query for voterId here
    // because voterId is generated by another react hook
    // so order is not guaranteed
    votes: {},
  })
  console.debug(data)

  // generate voterId
  const [voterId, setVoterId] = useState<string>()
  useEffect(() => {
    db.getLocalId("guest")
      .then((v) => setVoterId(v))
      .catch((e) => console.debug(e))
  }, [])
  console.debug(`id: ${voterId}`)

  if (!voterId) {
    return <p className="italic text-gray-700">Initializing...</p>
  }
  if (error) {
    console.debug(error)
    return <p className="italic text-gray-700">Please reload the page...</p>
  }
  if (isLoading) {
    return <p className="italic text-gray-700">Loading...</p>
  }

  const players = data.players as PlayerJson[]
  const playerLeft = players.find((p) => p.position === "left")
  const playerRight = players.find((p) => p.position === "right")

  // find the vote[voterId]
  const myVote = (data.votes as VoteJson[]).find((v) => v.id === voterId)

  return (
    <>
      <div>Vote</div>
      <button
        onClick={() => {
          db.transact(db.tx.votes[voterId].update({ left: !myVote?.left }))
        }}
        disabled={!playerLeft}
      >
        {playerLeft
          ? voteOrUnvote(myVote?.left) + " for " + playerLeft?.name
          : "Loading..."}
      </button>
      <button
        onClick={() => {
          db.transact(db.tx.votes[voterId].update({ right: !myVote?.right }))
        }}
        disabled={!playerLeft}
      >
        {playerRight
          ? voteOrUnvote(myVote?.right) + " for " + playerRight?.name
          : "Loading..."}
      </button>

      <iframe
        src="https://challonge.com/18qssxzv/module"
        width="100%"
        height="500"
      ></iframe>
    </>
  )
}

function voteOrUnvote(voted: boolean | undefined) {
  return voted ? "unvote" : "vote"
}

export default Vote
